### ISSUE TITLE
Face liveness detection

### ISSUE THREAD

**Issue by Prasad2018** [Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework#42] opened 2018-08-28 10:13 UTC
While Trying to access with mobile photos , App recognition was granted. How do i make changes to not allow the mobile photos for accessing the application.

**Comment by NabanilC** [comment] 2018-10-29 10:10
> While Trying to access with mobile photos , App recognition was granted. How do i make changes to not allow the mobile photos for accessing the application.

Any update on this?

**Comment by sladomic** [comment] 2018-10-29 10:17
Duplicate of https://github.com/Qualeams/Android-Face-Recognition-with-Deep-Learning-Test-Framework/issues/45

**Closed as completed** 2018-10-29 13:34 UTC
